name: Docker Build & Push (Multi-Arch)

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/docker.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/florita1/ingestion-service:latest \
            -t ghcr.io/florita1/ingestion-service:v0.2.4 \
            --push .
